version: 2
jobs:
  build:
    macos:
      xcode: "12.0.0"

    steps:
      - checkout

      - run:
          name: Build
          command: fastlane run xcodebuild clean:true build:true scheme:"Lottie" destination:"generic/platform=iOS"

      - store_artifacts:
          path: ~/Library/Logs/fastlane
          destination: fastlane-logs
